102 scaffold filter
andremun/pyInstanceSpace pull request #127
Opened 2024-08-23 15:38 UTC by KIAND-glitch

- Create FilterPostPrelimOptions in options.py
- Create FilterPostPrelimOut in model.py
- Add FilterPostPrelimOptions, and init _filter_post_prelim() method in prelim.py
- Include FilterPostPrelimOptions in test_prelim.py

2024-08-25 13:32 UTC, neatht requested changes

2024-08-28 07:15 UTC, KushagraKhare0 reviewed
Great job, nothing too concerning here that hasn't been addressed

2024-08-28 07:16 UTC, neatht approved these changes

2024-08-28 07:16 UTC, KushagraKhare0 approved these changes

2024-08-28 07:23 UTC, merged