Pythia
andremun/pyInstanceSpace pull request #150
Opened 2024-09-19 01:48 UTC by Hazel-Yi

Pythia with old and new stage overhaul design
TODO:

- [x] Docstring with new design

2024-09-21 08:46 UTC, dhjang03 requested changes
Great work on migrating the Pythia to Python.

2024-09-22 10:13 UTC, dhjang03 approved these changes

2024-09-23 05:37 UTC, CZLam7 requested changes
I haven't finish reviewing it, will do after 3 hours

2024-09-23 12:19 UTC, CZLam7 approved these changes
Comments in Pythia stage is clear, I like how it's differentiate clearly into 4 stages that makes review process much easier. Docstring is short but sufficient to understand. Nice work

2024-09-23 13:23 UTC, closed without merging