PRELIM python implementation
andremun/pyInstanceSpace pull request #87
Opened 2024-05-10 04:28 UTC by KIAND-glitch

- prelim.py contains PRELIM.m python implementation
- test_prelim.py contains unit tests testing run, and prelim subfunctions
- tests/test_data/prelim contains the expected output imported from MATLAB
- data/model.py modified to capture correct type of min_y and mu_y as float and NDArray[np.double] respectively

2024-05-18 12:53 UTC, neatht requested changes

2024-05-27 06:23 UTC, Taozizz approved these changes
Apart from Nathan's comment, the implementation looks correct.

2024-05-28 23:22 UTC, ybguzel reviewed
Please answer the pending question. I am happy to approve once we clarify them.

2024-05-29 11:44 UTC, neatht requested changes

2024-05-30 06:54 UTC, ybguzel approved these changes

2024-05-30 07:20 UTC, neatht requested changes

2024-05-30 08:22 UTC, neatht approved these changes

2024-05-30 10:13 UTC, merged