Pilot dimensionality reduction
andremun/pyInstanceSpace pull request #93
Opened 2024-05-23 00:49 UTC by KushagraKhare0

The pilot file is still a work in progress - still needs to pass all tests

2024-08-05 11:07 UTC, KIAND-glitch requested changes
Hey @KushagraKhare0 I have added some comments to mainly pilot.py, could you please take a look :)

2024-08-07 14:04 UTC, neatht requested changes

2024-08-08 01:19 UTC, CZLam7 requested changes
Good work Kush, just some small suggestions and questions regarding one if-else statement sections. I reviewed mainly about the functionality u implemented instead of architecture.

2024-08-13 11:11 UTC, neatht requested changes

2024-08-14 08:15 UTC, neatht approved these changes

2024-08-14 08:18 UTC, KIAND-glitch approved these changes

2024-08-14 08:22 UTC, CZLam7 approved these changes

2024-08-14 08:54 UTC, merged